// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPRYy1_X79-ilEHxT_VxjpUYqy-adOpHo',
    appId: '1:284584943565:web:cea32e6795f3d89ed5ee84',
    messagingSenderId: '284584943565',
    projectId: 'nm-dress',
    authDomain: 'nm-dress.firebaseapp.com',
    storageBucket: 'nm-dress.firebasestorage.app',
    measurementId: 'G-NND3GN8EZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgjoUcbAHR4eu4LyryWACGjKmol_hhab8',
    appId: '1:284584943565:android:167d113431f8f3c8d5ee84',
    messagingSenderId: '284584943565',
    projectId: 'nm-dress',
    storageBucket: 'nm-dress.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Pm5j0URjpYZ0faNWFWSdOdy2z5M-hZs',
    appId: '1:284584943565:ios:9a94fa71ddb994e0d5ee84',
    messagingSenderId: '284584943565',
    projectId: 'nm-dress',
    storageBucket: 'nm-dress.firebasestorage.app',
    iosClientId: '284584943565-09trtihikrdr9v3vftpq6otjejk7o0un.apps.googleusercontent.com',
    iosBundleId: 'com.nmdresshatay.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Pm5j0URjpYZ0faNWFWSdOdy2z5M-hZs',
    appId: '1:284584943565:ios:9a94fa71ddb994e0d5ee84',
    messagingSenderId: '284584943565',
    projectId: 'nm-dress',
    storageBucket: 'nm-dress.firebasestorage.app',
    iosClientId: '284584943565-09trtihikrdr9v3vftpq6otjejk7o0un.apps.googleusercontent.com',
    iosBundleId: 'com.nmdresshatay.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPRYy1_X79-ilEHxT_VxjpUYqy-adOpHo',
    appId: '1:284584943565:web:298dcc1e204f8735d5ee84',
    messagingSenderId: '284584943565',
    projectId: 'nm-dress',
    authDomain: 'nm-dress.firebaseapp.com',
    storageBucket: 'nm-dress.firebasestorage.app',
    measurementId: 'G-V8H0C4ZEQD',
  );
}
